contact_links:
  - name: â” Questions / Help
    url: https://github.com/xM-1/kiro-music
    about: Please use the new GitHub Discussions forum for help and questions, do not start an issue.
  - name: ğŸ“ƒ Discord Server
    url: https://discord.gg/D8bvhSsfCm
    about: The official Discord for Kiro.
